spring:
  zipkin:
    base-uri: http://127.0.0.1:9411/


eureka:
  client:
    registry-with-eureka: true
    registry-fetch: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
my:
  message: Hello Mouni
